# -*- coding: utf-8 -*-
"""tugas3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13RkrV8HDOOwGB49Nep4Mn1x-oOK0vx9z
"""

import numpy as np
import matplotlib.pyplot as plt

data = np.random.rand(1024, 2)
plt.scatter(data[:,0], data[:,1])
plt.show()